language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  nosetests --with-coverage --cover-package=tests && coverage report
after_success:
  - coveralls
services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
addons:
  postgresql: "9.6"
