"""empty message

Revision ID: 164ff1eba911
Revises: b3eae467e083
Create Date: 2017-07-28 12:42:18.120000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164ff1eba911'
down_revision = 'b3eae467e083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column(u'bucketlists', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bucketlists', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucketlists', type_='foreignkey')
    op.drop_column(u'bucketlists', 'created_by')
    op.drop_table('users')
    # ### end Alembic commands ###
